accounts/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path

from . import views


urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "login/", auth_views.LoginView.as_view(template_name="login.html"), name="login"
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "reset/",
        auth_views.PasswordResetView.as_view(
            template_name="password_reset.html",
            email_template_name="password_reset_email.html",
            subject_template_name="password_reset_subject.txt",
        ),
        name="password_reset",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

notebooks/urls.py
from django.urls import path

from . import views

app_name = "notebooks"

urlpatterns = [
    path("<str:pk>/notes", views.NoteListView.as_view(), name="notes_list"),
    path("create", views.notebook_create_popup, name="create_notebook"),
    path("<str:pk>/update", views.NotebookUpdateView.as_view(), name="update_notebook"),
]

notes/urls.py
from django.urls import path

from . import views

app_name = "notes"

urlpatterns = [
    path("create", views.NoteCreateView.as_view(), name="create"),
    path(
        "<str:pk>/update/<str:note_pk>", views.NoteUpdateView.as_view(), name="update"
    ),
    path(
        "<str:pk>/delete/<str:note_pk>", views.NoteDeleteView.as_view(), name="delete"
    ),
]

notes_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("notes/", include("notes.urls")),
    path("notebooks/", include("notebooks.urls")),
    path("accounts/", include("accounts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

notes/models.py
from django.db import models

from taggit.managers import TaggableManager
from model_utils.models import TimeStampedModel


class Notebook(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Note(TimeStampedModel):
    title = models.CharField(max_length=100)
    body = models.TextField()
    notebook = models.ForeignKey(
        Notebook, blank=True, null=True, on_delete=models.CASCADE
    )
    tag = TaggableManager(blank=True)

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

notebooks/forms.py
from django import forms
from django.db.models import fields


from notes.models import Note, Notebook


class NotebookForm(forms.ModelForm):
    class Meta:
        model = Notebook
        fields = ["name"]

notes/forms.py
from django import forms

from notes.models import Note, Notebook


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ["title", "body", "notebook", "tag"]
        widgets = {
            "body": forms.Textarea(attrs={"rows": 20, "cols": 60}),
        }

accounts/views.py
from django.views.generic import CreateView
from django.shortcuts import render
from django.contrib.auth.models import User
from django.urls import reverse_lazy


from .forms import SignUpForm
from notes.models import Notebook


class SignUpView(CreateView):
    template_name = "signup.html"
    success_url = reverse_lazy("login")
    form_class = SignUpForm

notebooks/views.py
from django.views.generic import ListView, UpdateView
from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from notes.models import Notebook, Note
from .forms import NotebookForm


@method_decorator(login_required, name="dispatch")
class NoteListView(ListView):
    model = Note
    paginate_by = 6
    context_object_name = "notes"
    template_name = "notes/note_list.html"

    def get_queryset(self):
        notebook = get_object_or_404(Notebook, pk=self.kwargs.get("pk"))
        if self.request.GET.get("tags"):
            query_tags = self.request.GET.get("tags").split(",")
            return Note.objects.filter(tag__name__in=query_tags, notebook=notebook)
        return Note.objects.filter(notebook=notebook)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["notebooks"] = Notebook.objects.annotate(Count("note"))
        return context


@login_required
def notebook_create_popup(request):
    form = NotebookForm(request.POST or None)
    if form.is_valid():
        instance = form.save()
        return HttpResponse(
            '<script>opener.closePopup(window, "%s", "%s", "#id_notebook");</script>'
            % (instance.pk, instance)
        )
    else:
        return render(request, "notes/create_notebook.html", {"form": form})


@method_decorator(login_required, name="dispatch")
class NotebookUpdateView(UpdateView):
    model = Notebook
    form_class = NotebookForm
    template_name = "notes/create_notebook.html"

    def get_success_url(self):
        return reverse("notebooks:notes_list", args=[self.kwargs.get("pk")])

notes/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from .forms import NoteForm
from .models import Note


@method_decorator(login_required, name="dispatch")
class NoteCreateView(CreateView):
    form_class = NoteForm
    template_name = "notes/create_note.html"

    def form_valid(self, form):
        self.selected_notebook = form.cleaned_data["notebook"]
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("notebooks:notes_list", args=[str(self.selected_notebook.id)])


@method_decorator(login_required, name="dispatch")
class NoteUpdateView(UpdateView):
    model = Note
    form_class = NoteForm
    pk_url_kwarg = "note_pk"
    template_name = "notes/create_note.html"

    def get_success_url(self):
        return reverse("notebooks:notes_list", args=[self.kwargs.get("pk")])


@method_decorator(login_required, name="dispatch")
class NoteDeleteView(DeleteView):
    model = Note
    pk_url_kwarg = "note_pk"
    template_name = "notes/delete.html"

    def get_success_url(self):
        messages.success(self.request, "Note was deleted successfully.")
        return reverse("notebooks:notes_list", args=[self.kwargs.get("pk")])

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body class = "bg-gray-100">
        <div class = "bg-gray-800 grid grid-flow-col justify-items-start space-x-3">
            <div class = " w-2/3 ">
                <h2 class="p-4 font-bold font-sans text-4xl text-white">
                Notes
                </h2>
            </div>
            <div class = "flex w-full justify-end space-x-3">
                <a class="p-6 font-bold text-white object-left" href= "{%url 'notes:create' %}">Create Note</a>

            </div>
          </div>
        <div class = "container mx-auto" >
            {% block content %}
            {% endblock content %}
        </div>
    
    </body>
</html>

templates/base_accounts.html
<head>
  <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

{% load static %}
{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      Notes
    </h1>
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

templates/login.html
{% extends 'base_accounts.html' %}
{% load myfilters %}
{% load static %}
{% block body %}  
  <div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
      <div>
        <img class="mx-auto h-12 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="Workflow">
        <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
          Sign in to your account
        </h2>
        <p class="mt-2 text-center text-sm text-gray-600">
          Or
          <a href="{% url 'signup' %}" class="font-medium text-indigo-600 hover:text-indigo-500">
            Sign up if you're new
          </a>
        </p>
      </div>
      <form class="mt-8 space-y-6" method="POST">
        {% csrf_token %}
        <div class="rounded-md shadow-sm -space-y-px">
          <div>
            <label class="sr-only">Email address</label>
                {{form.username|addclass:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"}}
          </div>
          <div>
            <label for="password" class="sr-only">Password</label>
                {{form.password|addclass:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" }}
          </div>
        </div>
  
        <div class="flex items-center justify-between">
          <div class="flex items-center">
          </div>
  
          <div class="text-sm">
            <a href="{% url 'password_reset' %}" class="font-medium text-indigo-600 hover:text-indigo-500">
              Forgot your password?
            </a>
          </div>
        </div>
  
        <div>
          <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            <span class="absolute left-0 inset-y-0 flex items-center pl-3">
              <svg class="h-5 w-5 text-indigo-500 group-hover:text-indigo-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
              </svg>
            </span>
            Sign in
          </button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

templates/notes/create_note.html
{% extends "base.html" %}

{% block content %}
{% load myfilters %}
{% load static %}
<head>
    <script src = "https://code.jquery.com/jquery-1.12.2.js"
    integrity="sha256-VUCyr0ZXB5VhBibo2DkTVhdspjmxUgxDGaLQx7qb7xY="
    crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/3.0.4/marked.min.js" integrity="sha512-a+W0h6Sho4fGYABZAQg6zdWP/qtyE+gzeVfNB/UApXRLuHKh7bT3TeA/LUOno+pcDjX0Vfzgtz6crFQC3YL9lA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>

<link rel="stylesheet" href= "{% static 'notes/headers.css' %}">
<div>
    <form method = "POST">
        {% csrf_token %}
        <div class = "grid grid-cols-7 ">
            <div class = "col-span-1" >
                <div>
                    <label class="block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2">
                        Title:
                    </label>
                </div>
                <div>
                    {{form.title|addclass:"title box-border border-2 border-indigo-900 max-w-lg block focus:ring-indigo-500 focus:border-indigo-500 w-full shadow-sm sm:max-w-xs sm:text-sm border-gray-300 rounded-md"}}
                </div>
                <div class = "mt-2">
                    <label class="block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2">
                        Notebook:
                    </label>
                </div> 
                <div>
                    {{form.notebook|addclass:"box-border border-2 border-indigo-900 max-w-lg block focus:ring-indigo-500 focus:border-indigo-500 w-full shadow-sm sm:max-w-xs sm:text-sm border-gray-300 rounded-md"}}
                    <a href={% url 'notebooks:create_notebook' %} id="add_notebook" onclick="return showAddPopup(this);"><img width="15px" class = "mt-2" src = "{% static '/notes/icon-addlink.svg' %}"></a>
                </div> 
                <div class = "mt-2">
                    <label class="block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2">
                        Tag:
                    </label>
                </div>
                <div>
                    {{form.tag|addclass:"box-border border-2 border-indigo-900 max-w-lg block focus:ring-indigo-500 focus:border-indigo-500 w-full shadow-sm sm:max-w-xs sm:text-sm border-gray-300 rounded-md"}}
                </div>
            </div>
            <div class="col-span-3 ml-36 mt-6">
                {{form.body|addclass:"body p-2 shadow-lg box-border border-2 border-indigo-900 block focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm border-gray-300 rounded-md"}}
            </div>
        
            <div class = "col-span-3 p-2 ml-28 mt-6 bg-white shadow-lg box-border border-2 border-indigo-900 rounded-md">
                <h3 id="preview-title"></h3>
                <div id="preview-body"></div>
            </div>
        </div> 
        <div class="pt-5">
            <div class="flex justify-end">
            <button type="submit" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" value="Save">
                Save
            </button>
            </div>
        </div>   
    </form>
</div>
{% block scripts %}
<script src="{% static 'notes/open_and_close_popup.js' %}"></script>
<script src="{% static 'notes/markdown_to_html.js' %}"></script>
{% endblock scripts %}

{% endblock content %}

templates/notes/create_notebook.html
{% load myfilters %}
{% load static %}
<head>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<div class = "container mx-auto">
    <form method = "POST">
        {% csrf_token %}
        <label class="block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2">
            Name:
        </label>
        <div>
            {{form.name|addclass:"title box-border border-2 border-indigo-900 max-w-lg block focus:ring-indigo-500 focus:border-indigo-500 w-full shadow-sm sm:max-w-xs sm:text-sm border-gray-300 rounded-md"}}
            {{form.name.errors}}
        </div>
        <div class="pt-5">
            <div class="flex justify-end">
            <button type="submit" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" value="Save">
                Save
            </button>
            </div>
        </div>  
    </form>
</div>

templates/notes/delete.html
<head>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<div class = "container mx-auto">
<form method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete {{object}}?<p>
  <div class="p-5">
      <div class="flex justify-end gap-4">
        <button type="submit" class="ml-1 inline-flex justify-center py-2 px-5 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" value="Save">
          Delete
        </button>
        <button type="button" class="bg-white py-2 px-6 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" id="add_more">
          Cancel
        </button>
      </div>
    </div>
</form>
</div>

templates/notes/note_list.html
<head>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
{% load myfilters %}
{% load static %}

<div class="h-screen flex overflow-hidden bg-gray-100">
    <div class="fixed inset-0 flex z-40 md:hidden" role="dialog" aria-modal="true">
      <div class="fixed inset-0 bg-gray-600 bg-opacity-75" aria-hidden="true"></div>
      <div class="relative flex-1 flex flex-col max-w-xs w-full pt-5 pb-4 bg-gray-800">
        <div class="absolute top-0 right-0 -mr-12 pt-2">
        </div>


        <div class="mt-5 flex-1 h-0 overflow-y-auto">
        </div>
      </div>

      <div class="flex-shrink-0 w-14" aria-hidden="true">
      </div>
    </div>


    <div class="hidden md:flex md:flex-shrink-0">
      <div class="flex flex-col w-64">
        <div class="flex-1 flex flex-col min-h-0">
          <div class="flex items-center h-16 flex-shrink-0 px-4 bg-gray-900">
            <h1 class = "text-4xl text-white font-bold">Notes</h1>
          </div>
          <div class="flex-1 flex flex-col overflow-y-auto">
            <nav class="flex-1 px-2 py-4 bg-gray-800 space-y-1">
              <a href="{% url 'notes:create' %}" class="bg-gray-900 text-white group flex items-center px-2 py-2 text-sm font-bold rounded-md">
                Create Note
              </a>
            {% for notebook in notebooks %}
            <div class = "flex justify-end">
              <a href="{% url 'notebooks:notes_list' notebook.id %}" class="mx-6 text-gray-300 hover:bg-gray-700 hover:text-white group flex items-center px-2 py-2 text-sm font-medium rounded-md">
                {{notebook.name}}
                <span class="ml-4 p-4 px-2 py-1 text-green-800 text-xs font-medium bg-green-100 rounded-full">{{notebook.note__count}}</span>
            <a class = "px-1 py-1 text-green-800 text-xs font-medium bg-green-100 rounded-full" href = "{% url 'notebooks:update_notebook' notebook.id %}"><img width="10px"  src = "{% static '/notes/edit.svg' %}"></a>
            </a>
            </div>


            {% endfor %}
            </nav>
          </div>
        </div>
      </div>
    </div>
    <div class="flex flex-col w-0 flex-1 overflow-hidden">
      <div class="relative z-10 flex-shrink-0 flex h-16 bg-white shadow">
        <div class="flex-1 px-4 flex justify-between">
          <div class="flex-1 flex">
              <div class="relative w-full text-gray-400 focus-within:text-gray-600">
                <div class="absolute inset-y-0 left-0 flex items-center pointer-events-none">
                </div>
              </div>
          </div>
          <div class="ml-4 flex items-center md:ml-6">
            <div class="ml-3 relative">
              <div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <main class="flex-1 relative overflow-y-auto focus:outline-none">
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <div class="bg-indigo-700 pt-4 text-white" role="alert">
                    <li>{{ message }}</li>
                </div>
            {% endfor %}
        </ul>
    {% endif %}
        <div class="py-6">
          <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">
            <ul role="list" class="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
                {% for note in notes %}
                <div class = mt-5>
                    <li class="col-span-1 text-center bg-white rounded-lg shadow divide-y divide-gray-200">
                    <div class="mt-2 grid-cols-4 p-10">
                        <h3 class="mt-2 text-gray-900 text-sm font-medium"><a href = "{% url 'notes:update' note.notebook.id note.id %}">{{note.title}}</a></h3>
                        <dl class="mt-1">
                        <dd class="mt-2 text-gray-500 text-sm truncate">{{note.body}}</dd>
                        <dd class="mt-3 gap-2 inline-flex">
                            {% for tag in note.tag.all %} 
                            <span class="px-2 py-1 text-green-800 text-xs font-medium bg-green-100 rounded-full"><a href="{%url 'notebooks:notes_list' note.notebook.id %}?tags={{tag}}">{{tag}}</a></span>
                            {% empty %}
                            <span class="px-2 py-1 text-green-800 text-xs font-medium bg-green-100 rounded-full">Not Tagged</span>
                            {% endfor %}
                        </dd>
                        </dl>
                    </div>
                    <div>
                        <div class="-mt-px flex divide-x divide-gray-200">
                        <div class="-ml-px w-0 flex-1 flex">
                            <a href="{% url 'notes:delete' note.notebook.id note.id %}" class="relative w-0 flex-1 inline-flex items-center justify-center py-4 text-sm text-gray-700 font-medium border border-transparent rounded-br-lg hover:text-gray-500">
                            <span class="ml-1 text-red-500">Delete</span>
                            </a>
                        </div>
                        </div>
                    </div>
                    </li>
                </div>
                {% endfor %}
              </ul>
              {% include "pagination.html" %}
          </div>
        </div>
      </main>
    </div>
  </div>

templates/notes/notebook_list.html
{% extends "base.html" %}

{% block content %}
{% load myfilters %}

<ul role="list" class="mt-5 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
    {% for notebook in notebooks %}
        <li class="col-span-1 bg-white rounded-lg shadow divide-y divide-gray-200">
            <div class="w-full flex items-center justify-between p-6 space-x-6">
            <div class="flex-1 truncate">
                <div class="flex items-center space-x-3">
                <h3 class="text-gray-900 text-sm font-medium truncate"><a href="#">{{notebook.name}}</a></h3>
                </div>
                <p class="mt-1 text-gray-500 text-sm truncate">Number of notes available: {{notebook.note__count}}</p>
            </div>
            </div>
            <div>
            <div class="-mt-px flex divide-x divide-gray-200">
                <div class="w-0 flex-1 flex">
                <a href="#" class="relative -mr-px w-0 flex-1 inline-flex items-center justify-center py-4 text-sm text-gray-700 font-medium border border-transparent rounded-bl-lg hover:text-gray-500">
                    <span class="ml-3">Update</span>
                </a>
                </div>
                <div class="-ml-px w-0 flex-1 flex">
                <a href="#" class="relative w-0 flex-1 inline-flex items-center justify-center py-4 text-sm text-gray-700 font-medium border border-transparent rounded-br-lg hover:text-gray-500">
                    <span class="ml-3">Delete</span>
                </a>
                </div>
            </div>
            </div>
        </li>
    {% endfor %}
</ul>

{% include "pagination.html" %}
{% endblock content %}

templates/pagination.html
{% load myfilters %}
<div class = "pt-5 justify-end flex">
    {% if is_paginated %}
    <nav aria-label="Page navigation example" class="d-flex justify-content-center pt-3">
      <ul class="pagination">
        {% if page_obj.has_previous and page_obj.number != 2 %}
        <li class="bg-white border-gray-300 text-gray-500 hover:bg-gray-50 relative inline-flex items-center px-4 py-2 border text-sm font-medium"><a href="?{% url_replace request 'page' 1 %}" tabindex="-1" aria-disabled="true">First Page</a></li>
        {% endif %}
        {% if page_obj.has_previous %}
        <li class="bg-white border-gray-300 text-gray-500 hover:bg-gray-50 relative inline-flex items-center px-4 py-2 border text-sm font-medium"><a href="?{% url_replace request 'page' page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a></li>
        {% endif %}
        <li class="bg-white border-green-300 text-green-500 hover:bg-green-50 relative inline-flex items-center px-4 py-2 border text-sm font-medium"><a href="#">{{ page_obj.number }}</a></li>
        {% if page_obj.has_next %}
        <li class="bg-white border-gray-300 text-gray-500 hover:bg-gray-50 relative inline-flex items-center px-4 py-2 border text-sm font-medium"><a href="?{% url_replace request 'page' page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a></li>
        {% endif %}
        {% if page_obj.paginator.num_pages != page_obj.number and page_obj.paginator.num_pages != page_obj.next_page_number %}
        <li class="bg-white border-gray-300 text-gray-500 hover:bg-gray-50 relative inline-flex items-center px-4 py-2 border text-sm font-medium"><a class="page-link text-dark" href="?{% url_replace request 'page' page_obj.paginator.num_pages %}">Last Page</a></li>
        {% endif %}
      </ul>
    </nav>
    </div>
    {% endif %} 

templates/password_reset.html
{% load myfilters %}
{% load static %}
{% block content %}
<head>
  <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

    <div class="min-h-screen bg-gray-100 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
      <div class="sm:mx-auto sm:w-full sm:max-w-md">
        
        <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
          Reset your password
        </h2>
        </p>
      </div>
    
      <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
        <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
          <form class="space-y-6" method="POST">
            {% csrf_token %}
            <div>
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700">
                Email Address
              </label>
              <div class="mt-1">
                {{form.email|addclass:"appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"}}
              </div>
            </div>
  
            <div class="flex items-center justify-between">
              <div class="flex items-center">
              </div>
              <div class="text-sm">
              </div>
            </div>
            <div>
              <button type="submit" class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                Send Password Reset Mail
              </button>
            </div>
          </form>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}